### ISSUE TITLE
No annotations file available

### ISSUE THREAD

**Issue by aliman80** [nikhilvenkatkumsetty/TrashBox#1]
HI can you provide any annotations in coco json format please i want to use it for my experiment

**Comment by nikhilvenkatkumsetty** [comment]
Hi @aliman80,
We will be providing the annotations file and updating the dataset into train data and test data very soon.
Thank you.

**Comment by aliman80** [comment]
Hi, Thank you for you nice work and support,

Can you provide me annotation files as i want to work on this project.

**Comment by nikhilvenkatkumsetty** [comment]
Hi,
Unfortunately, the annotation files are still in progress due to the large dataset size, but I have provided the detection code available at https://github.com/nikhilvenkatkumsetty/TrashBox-VGG19_model.
I hope this helps.
