### ISSUE TITLE
 lr,no of iterations 

### ISSUE THREAD

**Issue by aliman80** [nikhilvenkatkumsetty/TrashBox#2]
Hi can you provide little more details as i can reproduce results with large no of iterations is it ok or should i stick to as mentioned in paper

**Comment by nikhilvenkatkumsetty** [comment]
Hi @aliman80,
We will be updating our dataset with an annotation file and providing train data and test data very soon.
Thank you

**Comment by nikhilvenkatkumsetty** [comment]
Hi @aliman80,
I think you might have got the wrong dataset, we haven't published any results related to lr or no. of iterations.
Thank you.

**Comment by aliman80** [comment]
Hi,

Extremely sorry for this, i messed up things. Again sorry and thanks again for your response.


regards,
Muhammad Ali
________________________________
