### ISSUE TITLE
Provision of Annotation files

### ISSUE THREAD

**Issue by aliman80** [nikhilvenkatkumsetty/TrashBox#3]
Hi Can you provide annotation files and and if possible your detection code. If detection code is not available please provide annotation files for the dataset so that i may use it for my detection task.

**Comment by nikhilvenkatkumsetty** [comment]
Hi, 
Unfortunately, the annotation files are still in progress due to the large dataset size, but I have provided the detection code available at https://github.com/nikhilvenkatkumsetty/TrashBox-VGG19_model.
